spring.application.name=order-service
server.port=8082

spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

io.getunleash.app-name=order-service
io.getunleash.instance-id=${HOSTNAME:local}
io.getunleash.environment=development
io.getunleash.api-url=${UNLEASH_API_URL}
io.getunleash.api-token=${UNLEASH_API_TOKEN}